### ISSUE TITLE
Nice Project!

### ISSUE THREAD

**Issue by bketelsen** [mkideal/onepw#2]
I tested it out tonight and love the concept, great way for me to share passwords between computers and even teammates.  It would be more useful if I didn't have to be in the `mypasswords` directory when using it though.  Would you consider a PR to make that location pull from an env variable?  

export ONEPW_DIR=~/passwords

**Comment by mkideal** [comment]
Good ideal! I will implement it.

**Comment by mkideal** [comment]
I add env variable ONEPW_FILE instead of ONEPW_DIR, e.g.

export ONEPW_FILE=~/passwords/password.data
